# Generated by Django 4.2.25 on 2025-11-21 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='logics',
            field=models.CharField(max_length=50),
        ),
    ]
