# Generated by Django 5.2.8 on 2025-12-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("e_diary", "0002_alter_student_logics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="logics",
            field=models.IntegerField(default=0),
        ),
    ]
