# Generated by Django 5.2.8 on 2025-12-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post", models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="name",
            new_name="Name",
        ),
    ]
